### ISSUE TITLE
Bug when authenticating password

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/libgksu#6]
When you enter the wrong password, you will be prompted to enter the password again, and if you enter the wrong password three times, you will receive a warning.
But after updating the language-pack-pt-base package, it introduces a bug, if you enter the wrong password is not asking you to enter the password again, simply the authentication screen disappears. Moving to another language works fine.

This is a translation error in the sudoers.mo file.

/usr/share/locale-langpack/pt_BR/LC_MESSAGES/sudoers.mo
LINE 6 - Sorry, try again. - Desculpe, tente novamente.
/usr/share/locale-langpack/pt/LC_MESSAGES/sudoers.mo
LINE 6 - Sorry, try again. - Desculpe, tente novamente.

OBS: I downloaded the Source and opened the PO file, I noticed that the line 6 when it is written (Sorry, try again) works without bug, when translated or write anything, it presents the error.

EXEMPLE:
If I write:
EN PT or PT-BR
Sorry, try again. --- Sinto muito, tente novamente. ----- bug
Sorry, try again. --- aaa ddd rrr. ---------------------- bug
Sorry, try again. --- xxx fff hhh. ---------------------- bug
Sorry, try again. --- Sorry, try again.------------------ not bug

I made a video to show the error: https://youtu.be/D22S7rTha9I
Use Mint 18.01 Base Ubuntu 16.04

Clem:
https://github.com/linuxmint/libgksu/blob/acd6967a022709bf1ab74b3d7eb1eaabd91ce26f/libgksu/libgksu.c#L2599

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/libgksu/commit/cdca179b631fcffcca7003e8a7dd53aebf69b203.

libgksu 2.0.13~pre1-7linuxmint5
http://packages.linuxmint.com/pool/upstream/libg/libgksu/

**Comment by GabrielMGitHub** [comment]
Up to the present time the bug is still present, I did not receive any update correcting the error.
